lint: {}
nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: "@fmobegi"
  description: A pipeline for characterising the Human Blood Group and Red Cell Antigens
    using Oxford Nanopore third-generation sequencing data.
  force: false
  is_nfcore: true
  name: abotyper
  org: nf-core
  outdir: .
  version: 1.0.0dev
