lint:
  files_unchanged:
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
  nextflow_config:
    - config_defaults:
        - params.fasta
        - params.fai
        - params.multiqc_logo
  nf_test_content: false
nf_core_version: 4.0.2
repository_type: pipeline
template:
  author: "@fmobegi"
  description: A pipeline for characterising the Human Blood Group and Red Cell Antigens
    using Oxford Nanopore third-generation sequencing data.
  force: false
  is_nfcore: true
  name: abotyper
  org: nf-core
  outdir: .
  version: 1.1.0
