contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #abotyper channel"
    url: https://nfcore.slack.com/channels/abotyper
    about: Discussion about the nf-core/abotyper pipeline
